sudo: required
dist: trusty
language: c
compiler: gcc
os: linux

before_script:
    - ./autogen.sh

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libsystemd-journal-dev
            - valgrind
            - autoconf
            - automake
            - libjson-c-dev

script:
    - ./configure && make && make distcheck
